[workspace]
members = [
    "rnote-compose",
    "rnote-fileformats",
    "rnote-engine",
    "rnote-cli",
    "rnote-ui",
]

[profile.dev]
opt-level = 2
debug = true

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1

[patch.crates-io]
# this patch fixes usvg's (v0.27.0) incorrect export jpg mime type
usvg = {git = "https://github.com/flxzt/resvg", branch = "v-0-27-0-jpeg_mime_fix"}