[package]
name = "rnote"
version = "0.1.4"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "rough-rs",
]

[dependencies]
rough-rs = { path = "./rough-rs" } 
num-derive = "0.3.3"
num-traits = "0.2.14"
rand = "0.8"
log = "0.4"
pretty_env_logger = "0.3"
anyhow = "1.0.44"
serde = {version = "1.0", features = ["derive", "rc"]}
serde_json = { version="1.0" }
regex = "1.5.4"
rayon = "1.5.1"
nalgebra = { version = "0.29", features = ["serde-serialize"] }
nalgebra-glm = { version = "0.15"}
parry2d-f64 = { version = "0.7", features = ["serde-serialize"] }
svg = "0.10.0"
gtk4 = {version = "0.3", features = ["v4_4"]}
adw = {version = "0.1.0-alpha-6", package="libadwaita"}
libadwaita-sys = "0.1.0-alpha-6"
once_cell = "1.8"
base64 = "0.13"
tuple-conv = "1.0"
image = "0.23"
tera = "1.12"
cairo-rs = {version = "0.14"}
librsvg = { git="https://gitlab.gnome.org/GNOME/librsvg" }
resvg = "0.18"
usvg = "0.18"
tiny-skia = "0.6.1"