on: [push, pull_request]

name: Continuous integration

jobs:
# For now can't run a check without a container. the app requires gtk >= 4.8, but ubuntu 22.04 is still on 4.6
#  check:
#    name: Check
#    runs-on: ubuntu-22.04
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#      - name: Install deps
#        run: |
#          sudo apt-get update
#          sudo apt-get install -y meson libgtk-4-1 libgtk-4-dev libadwaita-1-0 libadwaita-1-dev libpoppler-glib8 libpoppler-glib-dev poppler-data libasound2 libasound2-dev 
#      - name: toolchain
#        uses: actions-rs/toolchain@v1
#        with:
#          profile: minimal
#          toolchain: stable
#          override: true
#      - name: check
#        uses: actions-rs/cargo@v1
#        with:
#          command: check

  fmt:
    name: Rustfmt
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check